### ISSUE TITLE
Dialogs.open() changes cwd on some platforms

### ISSUE THREAD

**Issue by larsiusprime** [snowkit/linc_dialogs#7]
I don't know if this is a bug on OpenFL or on linc_dialogs, but basically:

1) Open a file with Dialogs.open() (you must actually select a file, not hit "cancel")
2) Try to load a bitmap data with Assets.getBitmapData

It will always be null.

Here's some repro code, a modified version of OpenFL's DisplayingABitmap demo:

```Haxe
package;


import dialogs.Dialogs;
import lime.app.Application;
import openfl.Assets;
import openfl.display.Bitmap;
import openfl.display.Sprite;
import openfl.system.System;


class Main extends Sprite {
	
	public function new () {
		
		super();
		
		var str = Dialogs.open("title");
		
		trace("file = " + str);
		
		var bmpData = Assets.getBitmapData ("assets/openfl.png");
		
		trace("bmpData = " + bmpData);
		
		var bitmap = new Bitmap (bmpData);
		addChild (bitmap);
		
		bitmap.x = (stage.stageWidth - bitmap.width) / 2;
		bitmap.y = (stage.stageHeight - bitmap.height) / 2;
		
	}
	
	
}
```

If you select "cancel", the image loads. If you select a file (any file) it will not load and the trace will similarly indicate that bmpData is null.

I wouldn't normally expect linc_dialogs to interfere with OpenFL's asset system like this, so that's why I'm not quite sure where the bug originates. I figured I'd start here because if I swap linc_dialogs with systools, the problem goes away.

(also, to be clear the error occurs with the latest versions of Lime & OpenFL, and using the next codebase, not legacy)

**Comment by jcward** [comment]
@larsiusprime the `str` variable in your example isn't used - I presume that's a typo?  The return is null if you press cancel.

Here's how I open a file in hxScout (from either a socket or File, both are `haxe.io.Input`):

    private static var file_types =
    [
     { ext:'hxt', desc:'HXTelemetry Session' },
     { ext:'flm', desc:'Flash Telemetry Session' }
    ];

    public static function do_open_dialog():String
    {
      var file = Dialogs.open('Load telemetry session', file_types);
      if (file!=null && sys.FileSystem.exists(file)) {
        var input:haxe.io.Input = File.read(file, true);
        inp.readBytes(buffer, 0, BUFFER_SIZE);
        ...

**Comment by larsiusprime** [comment]
@jcward: actually it's not a typo. I'm not actually trying to load a file at all. The issue being presented here is that if you invoke Dialogs.open() at all, as long as you select an actual file, forever after OpenFL's normal assets system no longer works.

**Comment by jcward** [comment]
Ah, I see. Fascinating. Perhaps trace out `Sys.getCwd()` before and after the `open()` - presumably it won't change, but who knows. There's not a lot of code beyond calling the underlying native dialogs.

Maybe also trace: `sys.FileSystem.exists("assets/openfl.png")`

**Comment by larsiusprime** [comment]
```
Main.hx:19: BEFORE :
Main.hx:20: cwd = T:\Development\Projects\testing\displayingabitmap\Export\windo
ws\cpp\bin/
Main.hx:21: asset exists on fs = true
Main.hx:22: Assets.exists() = true
Main.hx:26: AFTER :
Main.hx:27: cwd = C:\Users\larsiusprime\Pictures/
Main.hx:28: asset exists on fs = false
Main.hx:29: Assets.exists() = true
```

**Comment by jcward** [comment]
Fascinating, so the act of opening the dialog changes the working directory. I would think this shouldn't be so. I don't think that's the case on Linux or else I would have problems.

Sys also has a setCwd -- so I think with get before and set after the open(), you can work around this issue. Presumably we should build that in, though. One possible wrinkle, however -- if the filename returned is relative to the new CWD. so perhaps we should:

1) Save off CWD
2) call open dialog
3) if result is not null, prepend new CWD to get an absolute path
4) reset CWD to original

**Comment by larsiusprime** [comment]
That workaround solves it, hope you can fix the underlying glitch in linc :)

**Comment by underscorediscovery** [comment]
(I don't consider OS dialog behaviour “glitches” fwiw.)

It seems reasonable to preserve the working directory, 
although it will be a flag-like setting (default true), no forced behaviour paths :)

**Comment by underscorediscovery** [comment]
Let me know if that helps @larsiusprime

**Comment by larsiusprime** [comment]
Excellent work, @underscorediscovery , that works perfectly!

**Comment by jcward** [comment]
@larsiusprime - by "it works perfectly" I assume you mean the above test doesn't fail anymore (which doesn't actually access the `str` file.)

If you still have this test sitting around, can you choose a pic in your Documents/Pictures folder and `trace(str)` ? I'm still concerned it _could_ return a relative path (maybe not!). We should test this on all platforms.
